### ISSUE TITLE
Java 11 broken jar file

### ISSUE THREAD

**Issue by ipkpjersi** [patrickfav/bcrypt#30]
Whenever I use this library in Java 11 to build a jar with Intellij, it says my main class is not found:
https://i.imgur.com/5XUaAll.png

When the main class clearly does exist, with the correct packaging: 
https://i.imgur.com/E5xhSNG.png

When using JBCrypt 0.4 instead, my jar file works fine, but JBCrypt doesn't support the newer $2y BCrypt version, only $2a.

**Comment by patrickfav** [comment]
Hi @ipkpjersi 

Thanks for the bug report.

I'm a little confused though, it seems the missing class is from your codebase, so I don't see how this library could influence that issue? The only hunch I have is if you use OSGi (I added a feature supporting it by a feature request - but it shouldn't influence non-OSGi)

**Comment by ipkpjersi** [comment]
I know, it confused me too. It does say the missing class is from my code-base, but, I did narrow it down to this BCrypt library *or* the Bytes library that this library depends on. If I remove BCrypt and Bytes and just use JBCrypt, it works fine.

**Comment by patrickfav** [comment]
Thanks for telling me, appreciate it. TBF there are not a lot of tests using Java11 so maybe something is broken - I will leave this open and will test in the near future for possible issues.

Have a good one!

**Comment by RohanNagar** [comment]
For what it's worth I just replaced jbcrypt with this library in my Java 11 application and it's working great!

**Comment by LionZXY** [comment]
This problem too :(

**Comment by patrickfav** [comment]
So unfortunately with this much information I cant really investigate, if one of you have some pointer where to look, or a test case I might be able to fix that.

**Comment by FinnTAstiK** [comment]
Hi Patrick,

What is happening to the individuals for this issue is they did not include your other library, 'Bytes', which is necessary for your Bcrypt library to work.  I included Bytes in my library and imported it, and this worked successfully.  There is no problem here.

Thanks for your work, it is much appreciated.

**Comment by HorizonCode** [comment]
Also having the same issue with Java8 in IntelliJ.
added it via maven pom.xml.
Luyten thows this exception if trying to decompile:
```java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at sun.security.util.SignatureFileVerifier.processImpl(Unknown Source)
	at sun.security.util.SignatureFileVerifier.process(Unknown Source)
	at java.util.jar.JarVerifier.processEntry(Unknown Source)
	at java.util.jar.JarVerifier.update(Unknown Source)
	at java.util.jar.JarFile.initializeVerifier(Unknown Source)
	at java.util.jar.JarFile.getInputStream(Unknown Source)
	at com.strobel.assembler.metadata.JarTypeLoader.tryLoadType(JarTypeLoader.java:59)
	at us.deathmarine.luyten.LuytenTypeLoader.tryLoadType(LuytenTypeLoader.java:25)
	at com.strobel.assembler.metadata.MetadataSystem.resolveType(MetadataSystem.java:125)
	at com.strobel.assembler.metadata.MetadataSystem.lookupTypeCore(MetadataSystem.java:86)
	at com.strobel.assembler.metadata.MetadataResolver.lookupType(MetadataResolver.java:46)
	at us.deathmarine.luyten.Model.openEntryByTreePath(Model.java:338)
	at us.deathmarine.luyten.Model$TreeListener$1.run(Model.java:266)
```

**Comment by NathanPB** [comment]
Just to address, this issue was happening with the Firebase Admin library too. I still don't have any decent workaround

https://stackoverflow.com/questions/64440041/firebase-admin-sdk-causing-cannot-find-or-load-main-class
